# Generated by Django 5.0.6 on 2026-05-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lab_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
