# Generated by Django 5.0.6 on 2026-05-03 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_lab_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lab_type',
        ),
    ]
