# Generated by Django 5.0.6 on 2026-05-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_lab_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lab_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
