# Generated by Django 5.0.6 on 2026-05-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_lab_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lab_type',
        ),
    ]
