# Generated by Django 6.0.4 on 2026-04-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_no', models.PositiveIntegerField(help_text='Sequential question number', unique=True)),
                ('question_type', models.CharField(choices=[('yes_no', 'Yes / No'), ('multiple_choice', 'Multiple Choice'), ('text', 'Free Text'), ('rating', 'Rating Scale')], default='yes_no', max_length=20)),
                ('question', models.TextField(help_text='The question text shown to the user')),
                ('explanation', models.TextField(blank=True, help_text='Why this question matters / regulatory context')),
                ('guidance_for_yes', models.TextField(blank=True, help_text='Guidance text when answer is Yes / compliant')),
                ('guidance_for_no', models.TextField(blank=True, help_text='Guidance text when answer is No / non-compliant')),
                ('remarks', models.TextField(blank=True, help_text='Internal remarks / notes for assessors')),
                ('gaps', models.TextField(blank=True, help_text='Known gaps or areas to address')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete / hide from assessments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['q_no'],
            },
        ),
    ]
