# Generated by Django 5.0.6 on 2026-04-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='gaps',
        ),
        migrations.RemoveField(
            model_name='question',
            name='guidance_for_no',
        ),
        migrations.RemoveField(
            model_name='question',
            name='guidance_for_yes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='remarks',
        ),
        migrations.AddField(
            model_name='question',
            name='feedback_for_no',
            field=models.TextField(blank=True, help_text='Feedback text when answer is No / non-compliant'),
        ),
        migrations.AddField(
            model_name='question',
            name='feedback_for_yes',
            field=models.TextField(blank=True, help_text='Feedback text when answer is Yes / compliant'),
        ),
        migrations.AddField(
            model_name='question',
            name='guidance',
            field=models.TextField(blank=True, help_text='Additional guidance or resources for this question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('yes_no', 'Yes / No'), ('objectives', 'Objectives')], default='yes_no', max_length=20),
        ),
    ]
