# Generated by Django 5.0.6 on 2026-04-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_question_gaps_remove_question_guidance_for_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='feedback_for_no',
            field=models.TextField(blank=True, help_text='Feedback text when   answer is No / non-compliant'),
        ),
    ]
