# Generated by Django 5.0.6 on 2026-05-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_feedback_for_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_section',
            field=models.CharField(blank=True, help_text='The section to which this question belongs', max_length=30),
        ),
    ]
