# Generated by Django 5.0.6 on 2026-05-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_question_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='q_no',
        ),
    ]
