# Generated by Django 5.0.6 on 2026-05-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_question_question_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
    ]
