# Generated by Django 5.0.6 on 2026-05-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_remove_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_section',
            field=models.CharField(blank=True, choices=[('Statutory Requirements', 'Statutory Requirements'), ('Physical Premises and Lab Space', 'Physical Premises and Lab Space'), ('Physical and Logical Security', 'Physical and Logical Security'), ('Fire and Electrical Hazard', 'Fire and Electric Hazard'), ('Support Services & Secure Storage', 'Support Services & Secure Storage'), ('Tools and Equipment', 'Tools and Equipment'), ('Manpower', 'Manpower'), ('Lab Management System', 'Lab Management System')], help_text='The section to which this question belongs', max_length=50),
        ),
    ]
