# Generated by Django 5.0.6 on 2026-06-03 12:52

import django.db.models.deletion
from django.db import migrations, models

def migrate_question_sections(apps, schema_editor):
    Question = apps.get_model('questions', 'Question')
    Section = apps.get_model('questions', 'Section')
    
    for q in Question.objects.all():
        section_name = q.question_section_old
        if section_name and section_name.strip():
            section_name = section_name.strip()
            # Find or create a Section with this name
            section, created = Section.objects.get_or_create(sectionName=section_name)
            q.question_section = section
            q.save()

class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_alter_question_question_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionName', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_section',
            new_name='question_section_old',
        ),
        migrations.AddField(
            model_name='question',
            name='question_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.section'),
        ),
        migrations.RunPython(migrate_question_sections, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='question',
            name='question_section_old',
        ),
    ]
