# Generated by Django 5.0.6 on 2026-06-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_section_alter_question_question_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=100)),
            ],
        ),
    ]
