# Generated by Django 5.0.6 on 2026-05-03 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['question__id']},
        ),
    ]
