# Generated by Django 5.0.6 on 2026-05-20 11:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0002_alter_response_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='scope',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, size=None),
        ),
    ]
